=== cf19santiago/public_html/actividades/Actividad7/7.2.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="artists">
       <xs:complexType>
           <xs:sequence>
               <xs:element name="performer" maxOccurs="unbounded" minOccurs="0" type="myType" />
           </xs:sequence>
       </xs:complexType>
   </xs:element>

   <xs:complexType name="myType">
       <xs:all>
           <xs:element type="xs:string" name="name" />
           <xs:element type="xs:string" name="nick" />
           <xs:element type="xs:string" name="born" />
       </xs:all>
   </xs:complexType>
</xs:schema>

=== cf19santiago/public_html/actividades/Actividad7/7.2.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<artists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./7.2.1.xsd">
   <performer>
       <nick>The redheaded priest</nick>
       <name>Antonio Vivaldi</name>
       <born>21-03-2022</born>
   </performer>
   <performer>
       <nick>El sugus sabor naranja</nick>
       <born>21-03-1685</born>
       <name>Johann Sebastian Bach</name>
   </performer>
</artists>
