=== cf19santiago/public_html/actividades/Actividad7/7.4.2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">
<xsd:element name="filmoteca"/>
<xsd:element name="peli" type="pelicula"/>
<xsd:complexType name="pelicula">
    <xsd:sequence>
        <xsd:element name="titol" type="xsd:string"/>
        <xsd:element name="director" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>
</xsd:schema>

=== cf19santiago/public_html/actividades/Actividad7/7.4.2.xml
<?xml version="1.0" encoding="UTF-8"?>		
<filmoteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./7.4.2.xsd">
  <peli>
    <titol>Amb faldes i a lo loco</titol>
    <director>Billy Wilder</director>
  </peli>
  <peli>		
    <titol>Sopa de goig</titol>
    <director>Leo McCarey</director>
  </peli>
  <autor>barto</autor>		
</filmoteca>
